# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

env:
  FORCE_COLOR: 2

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - { v: 22 }
          - { v: 24, isLatest: yes }

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Use Node.js ${{ matrix.node-version.v }}
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: ${{ matrix.node-version.v }}
    - run: npm clean-install
    - run: npm audit signatures
    - run: npm run all
    - run: npm run test

    - name: '[PR Preview] Upload dist folder'
      if: ${{github.event_name == 'pull_request' && matrix.node-version.isLatest}}
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: dist
        path: |
          dist

    - name: '[PR Preview] Store PR metadata'
      if: ${{github.event_name == 'pull_request' && matrix.node-version.isLatest}}
      run: |
        touch ./pr_metadata.ini
        echo "pr=${{github.event.number}}" >> ./pr_metadata.ini
        echo "ref=${{github.sha}}" >> ./pr_metadata.ini

    - name: '[PR Preview] Upload PR metadata'
      if: ${{github.event_name == 'pull_request' && matrix.node-version.isLatest}}
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: pr_metadata
        path: ./pr_metadata.ini
